// This file is generated by /src/generate_types/index.ts
import { ChildProcess } from 'child_process';
import { EventEmitter } from 'events';
/**
 * Can be converted to JSON
 */
interface Serializable {}
interface ConnectionTransport {}


/**
 * @param options 
 */
export function visit(options: [NavigationOptions]) : [Promise]<[void]>;


export interface By {
  /**
   * By.test
   */
  test: ;
}


